# Site settings
title: Fujun Du
email: fujun.du@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Astrophysics, mathematics, coding, etc.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  fjdu
orcid:  0000-0002-7489-0179

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "fenced_code_blocks"]

excerpt_separator: ""

plugins: [jekyll-paginate]
paginate: 25
paginate_path: "/blog/page:num/"
