# Site settings
title: Fujun Du
email: fujun.du@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Astrophysics, mathematics, coding, etc.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fjdu
github_username:  fjdu
orcid:  0000-0002-7489-0179

# Build settings
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "fenced_code_blocks"]

excerpt_separator: ""

plugins: [jekyll-paginate]
paginate: 25
paginate_path: "/blog/page:num/"

# Gitment
gitment:
  id: a6c3c265e2d16c71ef47
  secret: 40bc147ccb877da2a0070e67ddd544e66cba4fb8
